services:
  db:
    image: mysql:8.4
    container_name: ench_hist_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ench_hist
      MYSQL_USER: ench_user
      MYSQL_PASSWORD: ench_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ench_hist_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
